DROP TABLE IF EXISTS movies.users;
CREATE TABLE movies.users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username varchar(50) NOT NULL UNIQUE,
    user_name varchar(256) NOT NULL,
    user_email varchar(256) NOT NULL UNIQUE );

INSERT INTO movies.users VALUES
     (1, 'Facupyznar', 'Facundo', 'facupyznar@mail.com'),
     (2, 'Thiagosere', 'Thiago', 'thiagosere@mail.com'),
     (3, 'EliseoToledo', 'Eliseo', 'eliseoatoledo@mail.com'),
     (4, 'Nachopacheco', 'Ignacio', 'ipacheco@mail.com'),
     (5, 'Luchocalvani', 'Lucho', 'lcalvani@mail.com');


ALTER TABLE movies.users ALTER COLUMN user_id RESTART WITH 6;