DROP TABLE IF EXISTS movies.users;


CREATE TABLE movies.users (
      user_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_username  VARCHAR(50)   NOT NULL UNIQUE,
      user_name      VARCHAR(150)  NOT NULL,
      user_email     VARCHAR(320)  NOT NULL UNIQUE,
      password_hash  TEXT  NOT NULL,
      is_admin      BOOLEAN      NOT NULL DEFAULT FALSE
);



ALTER TABLE movies.users ALTER COLUMN user_id RESTART WITH 6;